name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write # لإعطاء صلاحية كتابة ملف الـ exe

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build Windows EXE
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Blended-Browser-EXE
        path: dist/*.exe
